//
// Generated by Bluespec Compiler (build 8d454e4)
//
// On Fri Oct  9 13:14:48 IST 2020
//
//
// Ports:
// Name                         I/O  size props
// fn_pmp_lookup                  O     7
// fn_pmp_lookup_req              I    34
// fn_pmp_lookup_priv             I     2
// fn_pmp_lookup_pmpcfg           I    32
// fn_pmp_lookup_pmpaddr          I   116
//
// Combinational paths from inputs to outputs:
//   (fn_pmp_lookup_req,
//    fn_pmp_lookup_priv,
//    fn_pmp_lookup_pmpcfg,
//    fn_pmp_lookup_pmpaddr) -> fn_pmp_lookup
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module module_fn_pmp_lookup(fn_pmp_lookup_req,
			    fn_pmp_lookup_priv,
			    fn_pmp_lookup_pmpcfg,
			    fn_pmp_lookup_pmpaddr,
			    fn_pmp_lookup);
  // value method fn_pmp_lookup
  input  [33 : 0] fn_pmp_lookup_req;
  input  [1 : 0] fn_pmp_lookup_priv;
  input  [31 : 0] fn_pmp_lookup_pmpcfg;
  input  [115 : 0] fn_pmp_lookup_pmpaddr;
  output [6 : 0] fn_pmp_lookup;

  // signals for module outputs
  wire [6 : 0] fn_pmp_lookup;

  // remaining internal signals
  reg [5 : 0] x__h2100;
  wire [28 : 0] mask__h1150,
		mask__h1151,
		mask__h1359,
		mask__h1360,
		mask__h442,
		mask__h443,
		mask__h941,
		mask__h942,
		start_address__h1149,
		start_address__h1358,
		start_address__h441,
		start_address__h940,
		x__h1089,
		x__h1115,
		x__h1298,
		x__h1324,
		x__h1507,
		x__h1533,
		x__h880,
		x__h907,
		y__h1090,
		y__h1299,
		y__h1508,
		y__h881;
  wire IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166,
       IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46,
       NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41,
       fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62,
       fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99,
       x__h1109,
       x__h1318,
       x__h1527,
       x__h901;

  // value method fn_pmp_lookup
  assign fn_pmp_lookup =
	     { NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169,
	       x__h2100 } ;

  // remaining internal signals
  assign IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 ||
	      fn_pmp_lookup_pmpcfg[4:3] == 2'd0) ?
	       (fn_pmp_lookup_pmpcfg[15] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[8] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[9] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[10]) :
	       (fn_pmp_lookup_pmpcfg[7] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[0] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[1] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[2]) ;
  assign IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 &&
	      (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 ||
	       !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 ||
	       fn_pmp_lookup_pmpcfg[20:19] == 2'd0)) ?
	       (fn_pmp_lookup_pmpcfg[31] || fn_pmp_lookup_priv != 2'd3) &&
	       (fn_pmp_lookup_req[1:0] == 2'd0 && !fn_pmp_lookup_pmpcfg[24] ||
		fn_pmp_lookup_req[1:0] == 2'd1 && !fn_pmp_lookup_pmpcfg[25] ||
		fn_pmp_lookup_req[1:0] == 2'd2 && !fn_pmp_lookup_pmpcfg[26]) :
	       (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 ?
		  (fn_pmp_lookup_pmpcfg[23] || fn_pmp_lookup_priv != 2'd3) &&
		  (fn_pmp_lookup_req[1:0] == 2'd0 &&
		   !fn_pmp_lookup_pmpcfg[16] ||
		   fn_pmp_lookup_req[1:0] == 2'd1 &&
		   !fn_pmp_lookup_pmpcfg[17] ||
		   fn_pmp_lookup_req[1:0] == 2'd2 &&
		   !fn_pmp_lookup_pmpcfg[18]) :
		  IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d166) ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d169 =
	     (NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 &&
	      fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 &&
	      fn_pmp_lookup_pmpcfg[20:19] != 2'd0 ||
	      NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88 &&
	      fn_pmp_lookup_pmpcfg[28:27] != 2'd0) &&
	     IF_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pm_ETC___d168 ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d46 =
	     !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 &&
	     fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 &&
	     fn_pmp_lookup_pmpcfg[4:3] != 2'd0 ||
	     !fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 &&
	     fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 &&
	     fn_pmp_lookup_pmpcfg[12:11] != 2'd0 ;
  assign NOT_fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_p_ETC___d88 =
	     fn_pmp_lookup_req[33:5] >=
	     (start_address__h1358 & mask__h1360) &&
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[115:87] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[28:0] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[57:29] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d64 =
	     fn_pmp_lookup_req[33:5] <= fn_pmp_lookup_pmpaddr[86:58] ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 =
	     fn_pmp_lookup_req[33:5] < (start_address__h441 & mask__h443) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 =
	     fn_pmp_lookup_req[33:5] < (start_address__h940 & mask__h942) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d62 =
	     fn_pmp_lookup_req[33:5] < (start_address__h1149 & mask__h1151) ;
  assign fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d99 =
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d17 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d19 ||
	      fn_pmp_lookup_pmpcfg[4:3] == 2'd0) &&
	     (fn_pmp_lookup_req_BITS_33_TO_5_ULT_IF_fn_pmp_l_ETC___d39 ||
	      !fn_pmp_lookup_req_BITS_33_TO_5_ULE_fn_pmp_look_ETC___d41 ||
	      fn_pmp_lookup_pmpcfg[12:11] == 2'd0) ;
  assign mask__h1150 = { fn_pmp_lookup_pmpaddr[85:58], x__h1318 } ;
  assign mask__h1151 =
	     (fn_pmp_lookup_pmpcfg[20:19] == 2'd3) ?
	       ~x__h1298 :
	       29'd536870911 ;
  assign mask__h1359 = { fn_pmp_lookup_pmpaddr[114:87], x__h1527 } ;
  assign mask__h1360 =
	     (fn_pmp_lookup_pmpcfg[28:27] == 2'd3) ?
	       ~x__h1507 :
	       29'd536870911 ;
  assign mask__h442 = { fn_pmp_lookup_pmpaddr[27:0], x__h901 } ;
  assign mask__h443 =
	     (fn_pmp_lookup_pmpcfg[4:3] == 2'd3) ? ~x__h880 : 29'd536870911 ;
  assign mask__h941 = { fn_pmp_lookup_pmpaddr[56:29], x__h1109 } ;
  assign mask__h942 =
	     (fn_pmp_lookup_pmpcfg[12:11] == 2'd3) ?
	       ~x__h1089 :
	       29'd536870911 ;
  assign start_address__h1149 =
	     (fn_pmp_lookup_pmpcfg[20:19] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[57:29] :
	       fn_pmp_lookup_pmpaddr[86:58] ;
  assign start_address__h1358 =
	     (fn_pmp_lookup_pmpcfg[28:27] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[86:58] :
	       fn_pmp_lookup_pmpaddr[115:87] ;
  assign start_address__h441 =
	     (fn_pmp_lookup_pmpcfg[4:3] == 2'd1) ?
	       29'd0 :
	       fn_pmp_lookup_pmpaddr[28:0] ;
  assign start_address__h940 =
	     (fn_pmp_lookup_pmpcfg[12:11] == 2'd1) ?
	       fn_pmp_lookup_pmpaddr[28:0] :
	       fn_pmp_lookup_pmpaddr[57:29] ;
  assign x__h1089 = mask__h941 & y__h1090 ;
  assign x__h1109 = ~(fn_pmp_lookup_pmpcfg[12:11] == 2'd2) ;
  assign x__h1115 = mask__h941 + 29'd1 ;
  assign x__h1298 = mask__h1150 & y__h1299 ;
  assign x__h1318 = ~(fn_pmp_lookup_pmpcfg[20:19] == 2'd2) ;
  assign x__h1324 = mask__h1150 + 29'd1 ;
  assign x__h1507 = mask__h1359 & y__h1508 ;
  assign x__h1527 = ~(fn_pmp_lookup_pmpcfg[28:27] == 2'd2) ;
  assign x__h1533 = mask__h1359 + 29'd1 ;
  assign x__h880 = mask__h442 & y__h881 ;
  assign x__h901 = ~(fn_pmp_lookup_pmpcfg[4:3] == 2'd2) ;
  assign x__h907 = mask__h442 + 29'd1 ;
  assign y__h1090 = ~x__h1115 ;
  assign y__h1299 = ~x__h1324 ;
  assign y__h1508 = ~x__h1533 ;
  assign y__h881 = ~x__h907 ;
  always@(fn_pmp_lookup_req)
  begin
    case (fn_pmp_lookup_req[1:0])
      2'd0: x__h2100 = 6'd5;
      2'd1: x__h2100 = 6'd7;
      default: x__h2100 = 6'd1;
    endcase
  end
endmodule  // module_fn_pmp_lookup

